Repository kubeclipper/kubeclipper.github.io, pull requests merged in 2022-12, with the labels that each got.

#30 update docs directory and fix jump between en and zh_cn
  content/en/docs/Faq/_index.md
  content/en/docs/Getting started/aio-env.md
  content/en/docs/Tutorials/access-control.md
  content/en/docs/Tutorials/cluster-hosting.md
  content/en/docs/Tutorials/cluster-management.md
  content/en/docs/Tutorials/create-clusters.md
  content/en/docs/Tutorials/node-management.md
  content/zh-cn/docs/Contribution guidelines/_index.md
  content/zh-cn/docs/Deployment docs/_index.md
  content/zh-cn/docs/Faq/_index.md
  content/zh-cn/docs/Getting started/_index.md
  content/zh-cn/docs/Tutorials/_index.md
Labels: dco-signoff: yes, approved, lgtm, size/M

#31 Geting started doc and fix copywriting guidelines
  content/en/_index.html
  content/en/docs/Getting started/aio-env.md
  content/en/docs/Getting started/carete-k8s-cluster-offline.md
  content/en/docs/Overview/_index.md
  content/en/docs/Tutorials/cluster-hosting.md
  content/en/docs/Tutorials/cluster-management.md
  content/en/docs/Tutorials/create-clusters.md
  content/en/docs/Tutorials/node-management.md
  content/zh-cn/_index.html
  content/zh-cn/docs/Contribution guidelines/_index.md
  content/zh-cn/docs/Faq/kcctl-create-cluster-error.md
  content/zh-cn/docs/Getting started/_index.md
  content/zh-cn/docs/Getting started/aio-env.md
  content/zh-cn/docs/Getting started/carete-k8s-cluster-offline.md
  content/zh-cn/docs/Overview/_index.md
  content/zh-cn/docs/Tutorials/Cluster-hosting.md
  content/zh-cn/docs/Tutorials/Cluster-management.md
  content/zh-cn/docs/Tutorials/Create-clusters.md
  content/zh-cn/docs/Tutorials/Node-Management.md
  content/zh-cn/docs/Tutorials/access-control.md
Labels: dco-signoff: yes, approved, lgtm, size/L

#32 update ha deploy doc
  content/en/docs/Deployment docs/ha-deploy.md
  content/en/docs/Deployment docs/ha-env.md
  content/zh-cn/docs/Deployment docs/ha-deploy.md
  content/zh-cn/docs/Deployment docs/ha-env.md
Labels: dco-signoff: yes, approved, lgtm, size/XL

#33 fix: modify getting-start moduel image path
  content/zh-cn/docs/Getting started/_index.md
Labels: dco-signoff: yes, approved, lgtm, size/XS

#34 release 1.3 doc
  scripts/builder/consts.py
Labels: dco-signoff: yes, approved, lgtm, size/XS
