Repository kubeclipper/kubeclipper.github.io, pull requests merged in 2022-08, with the labels that each got.

#4 update index page
  content/en/_index.html
  content/zh/_index.html
Labels: dco-signoff: yes, approved, lgtm, size/M

#6 create cluster offline docs
  .gitignore
  content/en/docs/Tutorials/carete-k8s-cluster-offline.md
  content/zh/docs/Tutorials/carete-k8s-cluster-offline.md
  static/images/docs/cluster-begin.png
  static/images/docs/cluster-config.png
  static/images/docs/cluster-finish.png
  static/images/docs/cluster-node-config.png
  static/images/docs/cluster-plugin-config-jwt.png
  static/images/docs/cluster-plugin-config-memory.png
  static/images/docs/cluster-plugin-install.png
  static/images/docs/cluster-storage-config.png
  static/images/docs/cluster-success.png
Labels: dco-signoff: yes, approved, lgtm, size/L

#8 feat: modify website
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  content/zh-cn/_index.html
Labels: approved, lgtm

#9 fix: update logo & favicon
  assets/icons/logo.svg
  content/en/_index.html
  content/zh-cn/community/_index.md
  static/favicons/android-144x144.png
  static/favicons/android-192x192.png
  static/favicons/android-36x36.png
  static/favicons/android-48x48.png
  static/favicons/android-72x72.png
  static/favicons/android-96x96.png
  static/favicons/apple-touch-icon-180x180.png
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
Labels: dco-signoff: yes, approved, lgtm, size/L

#10 change docs picture
  content/en/docs/Tutorials/carete-k8s-cluster-offline.md
  content/zh-cn/docs/Tutorials/carete-k8s-cluster-offline.md
  static/images/docs-tutorials/cluster-begin.png
  static/images/docs-tutorials/cluster-config.png
  static/images/docs-tutorials/cluster-finish.png
  static/images/docs-tutorials/cluster-node-config.png
  static/images/docs-tutorials/cluster-storage-config.png
  static/images/docs-tutorials/cluster-successful.png
Labels: dco-signoff: yes, approved, lgtm, size/M

#11 feat: add deploy ha env docs
  content/en/docs/Tutorials/ha-env.md
  content/zh-cn/docs/Tutorials/access-control.md
  content/zh-cn/docs/Tutorials/cluster-manage.md
  content/zh-cn/docs/Tutorials/ha-env.md
  content/zh-cn/docs/Tutorials/node-manage.md
Labels: dco-signoff: yes, approved, lgtm, size/L
