Repository kubeclipper/kubeclipper.github.io, pull requests merged in 2022-11, with the labels that each got.

#20 checkout v1.2 docs
  scripts/builder/consts.py
Labels: dco-signoff: yes, approved, lgtm, size/XS

#22 Update the style and layout
  content/en/docs/Contribution guidelines/_index.md
  content/en/docs/Deployment docs/_index.md
  content/en/docs/Getting started/_index.md
  content/en/docs/Getting started/aio_env.md
  content/en/docs/Overview/_index.md
  content/en/docs/Tutorials/_index.md
  content/en/docs/_index.md
  content/zh-cn/docs/Contribution guidelines/_index.md
  content/zh-cn/docs/Deployment docs/_index.md
  content/zh-cn/docs/Deployment docs/ha-env.md
  content/zh-cn/docs/Faq/_index.md
  content/zh-cn/docs/Faq/kcctl-create-cluster-error.md
  content/zh-cn/docs/Getting started/_index.md
  content/zh-cn/docs/Getting started/aio-env.md
  content/zh-cn/docs/Overview/_index.md
  content/zh-cn/docs/_index.md
  static/images/docs-faq/add-key.png
  static/images/docs-faq/create-cluster-error.png
  static/images/docs-faq/need-login.png
Labels: dco-signoff: yes, approved, lgtm, size/L

#21 feat: release 1.2
  .github/workflows/build-doc.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#24 Change the base branch of the workflow
  .github/workflows/build-doc.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XS

#27 update deploy aio doc
  content/en/docs/Getting started/aio_env.md
  content/zh-cn/docs/Getting started/aio-env.md
Labels: dco-signoff: yes, approved, lgtm, size/M
